site_name: vkpymusic docs

nav:
  - Home: index.md
  - API Reference:
    - Client: api/client.md
    - TokenReceiver: api/tokenreceiver.md
    - Service: api/service.md
    - .models: api/models.md
    - .vk_api: api/vk_api.md
    - .utils: api/utils.md
  - Installation: installation.md
  # - Usage: usage.md
  # - Examples: examples.md
  # - Contributing: contributing.md
  # - Changelog: changelog.md
  - License: license.md

theme:
  name: material
  language: en

plugins:
  - search
  - autorefs
  - mkdocstrings